volumes:
  rabbitmq-dev-volume:
    name: rabbitmq-dev-volume

services:
  rabbitmq-dev:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq-dev-volume:/var/lib/rabbitmq
